{% set name = "pypmml" %}
{% set version = "0.9.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypmml-{{ version }}.tar.gz
  sha256: 7ce234c86495c525b69f39e29934f87ad895d2a92d194b312c28b7e1f9694479

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - openjdk >=11
  run:
    - python >={{ python_min }}
    - openjdk >=11
    - py4j >=0.10.7
    

test:
  imports:
    - pypmml
    - pypmml.jars
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/autodeployai/pypmml
  summary: Python PMML scoring library
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - maxibor
